### ISSUE TITLE
'AVFrame' has no member named ...

### ISSUE THREAD

**Issue by laeubi** [anyc/avcut#11]
I get the following errors:

avcut.c:554:19: error: 'AVFrame' has no member named 'pkt_size'
       s->frames[j]->pkt_size, s->pkts[i].size,

avcut.c:701:61: error: 'AVFrame' has no member named 'pkt_duration'
     int64_t new_pts = sbuffer->last_pts + av_rescale_q(frame->pkt_duration,

Is my version of ffmpeg to old? Can you describe what versions (debian, gcc, ...), are needed to build avcut?

**Comment by laeubi** [comment]
I have tried with whezzy, jessie and stretch but no luck

**Comment by anyc** [comment]
I can compile it with ffmpeg 3.3.6 under Gentoo although I get many deprecation warnings. It should also work with older versions. There were only very few changes necessary for the v2 -> v3 transition. 

Unfortunately, it looks like it will not be easy to find proper replacements for the deprecated parts and I do not have much free time for this project.

**Comment by laeubi** [comment]
Thanks for the hint, I was able to build it with latest gentoo also! I'll try to provide some additional features if possible.
