### ISSUE TITLE
This doesn't compile with newer libavcodec

### ISSUE THREAD

**Issue by gCurse** [anyc/avcut#14]
I get the following errors:
`avcut.c:157:31: error: ‘CODEC_FLAG_GLOBAL_HEADER’ undeclared (first use in this function); did you mean ´AV_CODEC_FLAG_GLOBAL_HEADER´?`
and
`avcut.c:482:93: error: ‘CODEC_CAP_DELAY’ undeclared (first use in this function); did you mean ‘AV_CODEC_CAP_DELAY’?`
Two times each.

Seems libavcodec is too new?
libavcodec     58.18.100

The following works for me but I have no idea which lowest version introduced the change:
`#if LIBAVCODEC_VERSION_INT >= AV_VERSION_INT(58,18,100)`
`#define CODEC_FLAG_GLOBAL_HEADER AV_CODEC_FLAG_GLOBAL_HEADER`
`#define CODEC_CAP_DELAY AV_CODEC_CAP_DELAY`
`#endif`
EDIT: Found [this: line 38ff](https://github.com/meetecho/janus-gateway/blob/master/postprocessing/pp-h264.c). So its version 56.56.0??

**Comment by anyc** [comment]
I'm not sure either but it looks good. Thanks for the help!
