### ISSUE TITLE
Warning with gcc 8.2

### ISSUE THREAD

**Issue by rdorsch** [anyc/avcut#15]
Hi,

this is just a heads-up: I see lots of deprecated warnings when compiling avcut on Debian testing:

rd@h370:~/tmp.nobackup/avcut$ make
cc -Wall -DAVCUT_VERSION=\"0.4\" -I/usr/include/x86_64-linux-gnu -I/usr/include/x86_64-linux-gnu -I/usr/include/x86_64-linux-gnu -DAVCUT_PROFILE_DIRECTORY=\"/usr/share/avcut/profiles/\"    avcut.c  -lavcodec -lavformat -lavutil -o avcut
avcut.c: In function ‘encode_write_frame’:
avcut.c:141:4: warning: ‘pkt_pts’ is deprecated [-Wdeprecated-declarations]
    frame->pts, frame->pkt_pts, frame->pkt_dts, frame->pkt_size, av_get_picture_type_char(frame->pict_type),
    ^~~~~
In file included from /usr/include/x86_64-linux-gnu/libavcodec/avcodec.h:38,
                 from /usr/include/x86_64-linux-gnu/libavformat/avformat.h:319,
                 from avcut.c:28:
/usr/include/x86_64-linux-gnu/libavutil/frame.h:319:13: note: declared here
     int64_t pkt_pts;
             ^~~~~~~
avcut.c:142:4: warning: ‘codec’ is deprecated [-Wdeprecated-declarations]
    frame->pts * av_q2d(ostream->codec->time_base)
    ^~~~~
In file included from avcut.c:28:
/usr/include/x86_64-linux-gnu/libavformat/avformat.h:877:21: note: declared here
     AVCodecContext *codec;
                     ^~~~~
avcut.c:147:2: warning: ‘avcodec_encode_video2’ is deprecated [-Wdeprecated-declarations]
  ret = avcodec_encode_video2(ostream->codec, &enc_pkt, frame, &got_frame);
  ^~~
In file included from /usr/include/x86_64-linux-gnu/libavformat/avformat.h:319,
                 from avcut.c:28:
/usr/include/x86_64-linux-gnu/libavcodec/avcodec.h:5386:5: note: declared here
 int avcodec_encode_video2(AVCodecContext *avctx, AVPacket *avpkt,
     ^~~~~~~~~~~~~~~~~~~~~
avcut.c:147:2: warning: ‘codec’ is deprecated [-Wdeprecated-declarations]
  ret = avcodec_encode_video2(ostream->codec, &enc_pkt, frame, &got_frame);
  ^~~
In file included from avcut.c:28:
/usr/include/x86_64-linux-gnu/libavformat/avformat.h:877:21: note: declared here
     AVCodecContext *codec;
                     ^~~~~
avcut.c:158:4: warning: ‘codec’ is deprecated [-Wdeprecated-declarations]
    enc_pkt.duration = ostream->codec->ticks_per_frame;
    ^~~~~~~
In file included from avcut.c:28:
/usr/include/x86_64-linux-gnu/libavformat/avformat.h:877:21: note: declared here
     AVCodecContext *codec;
                     ^~~~~
avcut.c:160:3: warning: ‘codec’ is deprecated [-Wdeprecated-declarations]
   av_packet_rescale_ts(&enc_pkt, ostream->codec->time_base, ostream->time_base);
   ^~~~~~~~~~~~~~~~~~~~
In file included from avcut.c:28:
/usr/include/x86_64-linux-gnu/libavformat/avformat.h:877:21: note: declared here
     AVCodecContext *codec;
                     ^~~~~
avcut.c:166:3: warning: ‘codec’ is deprecated [-Wdeprecated-declarations]
   if (ostream->codec->flags & AV_CODEC_FLAG_GLOBAL_HEADER)
   ^~
In file included from avcut.c:28:
/usr/include/x86_64-linux-gnu/libavformat/avformat.h:877:21: note: declared here
     AVCodecContext *codec;
                     ^~~~~
avcut.c:167:4: warning: ‘av_bitstream_filter_filter’ is deprecated [-Wdeprecated-declarations]
    av_bitstream_filter_filter(pr->bsf_dump_extra, ostream->codec, NULL,
    ^~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/x86_64-linux-gnu/libavformat/avformat.h:319,
                 from avcut.c:28:
/usr/include/x86_64-linux-gnu/libavcodec/avcodec.h:5791:5: note: declared here
 int av_bitstream_filter_filter(AVBitStreamFilterContext *bsfc,
     ^~~~~~~~~~~~~~~~~~~~~~~~~~
avcut.c:167:4: warning: ‘codec’ is deprecated [-Wdeprecated-declarations]
    av_bitstream_filter_filter(pr->bsf_dump_extra, ostream->codec, NULL,
    ^~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from avcut.c:28:
/usr/include/x86_64-linux-gnu/libavformat/avformat.h:877:21: note: declared here
     AVCodecContext *codec;
                     ^~~~~
avcut.c: In function ‘frame_pts2ts’:
avcut.c:195:2: warning: ‘codec’ is deprecated [-Wdeprecated-declarations]
  return frame->pts * av_q2d(pr->in_fctx->streams[s->stream_index]->codec->time_base);
  ^~~~~~
In file included from avcut.c:28:
/usr/include/x86_64-linux-gnu/libavformat/avformat.h:877:21: note: declared here
     AVCodecContext *codec;
                     ^~~~~
avcut.c: In function ‘find_packet_for_frame’:
avcut.c:288:5: warning: ‘pkt_pts’ is deprecated [-Wdeprecated-declarations]
     s->pkts[i].pts == s->frames[frame_idx]->pkt_pts) ||
     ^
In file included from /usr/include/x86_64-linux-gnu/libavcodec/avcodec.h:38,
                 from /usr/include/x86_64-linux-gnu/libavformat/avformat.h:319,
                 from avcut.c:28:
/usr/include/x86_64-linux-gnu/libavutil/frame.h:319:13: note: declared here
     int64_t pkt_pts;
             ^~~~~~~
avcut.c:319:5: warning: ‘pkt_pts’ is deprecated [-Wdeprecated-declarations]
     s->frames[frame_idx]->pkt_pts,
     ^
In file included from /usr/include/x86_64-linux-gnu/libavcodec/avcodec.h:38,
                 from /usr/include/x86_64-linux-gnu/libavformat/avformat.h:319,
                 from avcut.c:28:
/usr/include/x86_64-linux-gnu/libavutil/frame.h:319:13: note: declared here
     int64_t pkt_pts;
             ^~~~~~~
avcut.c: In function ‘flush_packet_buffer’:
avcut.c:340:2: warning: ‘codec’ is deprecated [-Wdeprecated-declarations]
  if (pr->in_fctx->streams[s->stream_index]->codec->codec_type != AVMEDIA_TYPE_VIDEO) {
  ^~
In file included from avcut.c:28:
/usr/include/x86_64-linux-gnu/libavformat/avformat.h:877:21: note: declared here
     AVCodecContext *codec;
                     ^~~~~
avcut.c:465:7: warning: ‘codec’ is deprecated [-Wdeprecated-declarations]
       pr->in_fctx->streams[s->stream_index]->codec->time_base);
       ^~
In file included from avcut.c:28:
/usr/include/x86_64-linux-gnu/libavformat/avformat.h:877:21: note: declared here
     AVCodecContext *codec;
                     ^~~~~
avcut.c:485:5: warning: ‘av_frame_get_pkt_duration’ is deprecated [-Wdeprecated-declarations]
     s->duration_dropped_pkts += av_frame_get_pkt_duration(s->frames[i]);
     ^
In file included from /usr/include/x86_64-linux-gnu/libavcodec/avcodec.h:38,
                 from /usr/include/x86_64-linux-gnu/libavformat/avformat.h:319,
                 from avcut.c:28:
/usr/include/x86_64-linux-gnu/libavutil/frame.h:609:9: note: declared here
 int64_t av_frame_get_pkt_duration         (const AVFrame *frame);
         ^~~~~~~~~~~~~~~~~~~~~~~~~
avcut.c:491:3: warning: ‘codec’ is deprecated [-Wdeprecated-declarations]
   if (frame_written && pr->out_fctx->streams[s->stream_index]->codec->codec->capabilities & AV_CODEC_CAP_DELAY) {
   ^~
In file included from avcut.c:28:
/usr/include/x86_64-linux-gnu/libavformat/avformat.h:877:21: note: declared here
     AVCodecContext *codec;
                     ^~~~~
avcut.c:517:4: warning: ‘codec’ is deprecated [-Wdeprecated-declarations]
    AVCodecContext *out_cctx = pr->out_fctx->streams[s->stream_index]->codec;
    ^~~~~~~~~~~~~~
In file included from avcut.c:28:
/usr/include/x86_64-linux-gnu/libavformat/avformat.h:877:21: note: declared here
     AVCodecContext *codec;
                     ^~~~~
avcut.c:532:7: warning: ‘pkt_pts’ is deprecated [-Wdeprecated-declarations]
       s->pkts[i].pts == s->frames[j]->pkt_pts) ||
       ^
In file included from /usr/include/x86_64-linux-gnu/libavcodec/avcodec.h:38,
                 from /usr/include/x86_64-linux-gnu/libavformat/avformat.h:319,
                 from avcut.c:28:
/usr/include/x86_64-linux-gnu/libavutil/frame.h:319:13: note: declared here
     int64_t pkt_pts;
             ^~~~~~~
avcut.c:562:7: warning: ‘pkt_pts’ is deprecated [-Wdeprecated-declarations]
       s->frames[j]->pkt_pts,
       ^
In file included from /usr/include/x86_64-linux-gnu/libavcodec/avcodec.h:38,
                 from /usr/include/x86_64-linux-gnu/libavformat/avformat.h:319,
                 from avcut.c:28:
/usr/include/x86_64-linux-gnu/libavutil/frame.h:319:13: note: declared here
     int64_t pkt_pts;
             ^~~~~~~
avcut.c:573:6: warning: ‘codec’ is deprecated [-Wdeprecated-declarations]
      pr->in_fctx->streams[s->stream_index]->codec->time_base,
      ^~
In file included from avcut.c:28:
/usr/include/x86_64-linux-gnu/libavformat/avformat.h:877:21: note: declared here
     AVCodecContext *codec;
                     ^~~~~
avcut.c:595:5: warning: ‘codec’ is deprecated [-Wdeprecated-declarations]
     if (pr->in_fctx->streams[s->stream_index]->codec->opaque &&
     ^~
In file included from avcut.c:28:
/usr/include/x86_64-linux-gnu/libavformat/avformat.h:877:21: note: declared here
     AVCodecContext *codec;
                     ^~~~~
avcut.c:596:15: warning: ‘codec’ is deprecated [-Wdeprecated-declarations]
      ((struct codeccontext*) pr->in_fctx->streams[s->stream_index]->codec->opaque)->h264_avcc_format)
               ^~~~~~~~~~~~
In file included from avcut.c:28:
/usr/include/x86_64-linux-gnu/libavformat/avformat.h:877:21: note: declared here
     AVCodecContext *codec;
                     ^~~~~
avcut.c:598:6: warning: ‘av_bitstream_filter_filter’ is deprecated [-Wdeprecated-declarations]
      av_bitstream_filter_filter(pr->bsf_h264_to_annexb,
      ^~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/x86_64-linux-gnu/libavformat/avformat.h:319,
                 from avcut.c:28:
/usr/include/x86_64-linux-gnu/libavcodec/avcodec.h:5791:5: note: declared here
 int av_bitstream_filter_filter(AVBitStreamFilterContext *bsfc,
     ^~~~~~~~~~~~~~~~~~~~~~~~~~
avcut.c:599:7: warning: ‘codec’ is deprecated [-Wdeprecated-declarations]
       pr->in_fctx->streams[s->stream_index]->codec, NULL,
       ^~
In file included from avcut.c:28:
/usr/include/x86_64-linux-gnu/libavformat/avformat.h:877:21: note: declared here
     AVCodecContext *codec;
                     ^~~~~
avcut.c: In function ‘decode_packet’:
avcut.c:663:2: warning: ‘codec’ is deprecated [-Wdeprecated-declarations]
  mtype = pr->in_fctx->streams[stream_index]->codec->codec_type;
  ^~~~~
In file included from avcut.c:28:
/usr/include/x86_64-linux-gnu/libavformat/avformat.h:877:21: note: declared here
     AVCodecContext *codec;
                     ^~~~~
avcut.c:672:3: warning: ‘avcodec_decode_video2’ is deprecated [-Wdeprecated-declarations]
   ret = avcodec_decode_video2(pr->in_fctx->streams[stream_index]->codec, frame, &got_frame, packet);
   ^~~
In file included from /usr/include/x86_64-linux-gnu/libavformat/avformat.h:319,
                 from avcut.c:28:
/usr/include/x86_64-linux-gnu/libavcodec/avcodec.h:4755:5: note: declared here
 int avcodec_decode_video2(AVCodecContext *avctx, AVFrame *picture,
     ^~~~~~~~~~~~~~~~~~~~~
avcut.c:672:3: warning: ‘codec’ is deprecated [-Wdeprecated-declarations]
   ret = avcodec_decode_video2(pr->in_fctx->streams[stream_index]->codec, frame, &got_frame, packet);
   ^~~
In file included from avcut.c:28:
/usr/include/x86_64-linux-gnu/libavformat/avformat.h:877:21: note: declared here
     AVCodecContext *codec;
                     ^~~~~
avcut.c:692:4: warning: ‘av_frame_get_best_effort_timestamp’ is deprecated [-Wdeprecated-declarations]
    frame->pts = av_frame_get_best_effort_timestamp(frame);
    ^~~~~
In file included from /usr/include/x86_64-linux-gnu/libavcodec/avcodec.h:38,
                 from /usr/include/x86_64-linux-gnu/libavformat/avformat.h:319,
                 from avcut.c:28:
/usr/include/x86_64-linux-gnu/libavutil/frame.h:605:9: note: declared here
 int64_t av_frame_get_best_effort_timestamp(const AVFrame *frame);
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
avcut.c:701:4: warning: ‘pkt_pts’ is deprecated [-Wdeprecated-declarations]
    if (frame->pts == frame->pkt_dts || frame->pts == frame->pkt_pts)
    ^~
In file included from /usr/include/x86_64-linux-gnu/libavcodec/avcodec.h:38,
                 from /usr/include/x86_64-linux-gnu/libavformat/avformat.h:319,
                 from avcut.c:28:
/usr/include/x86_64-linux-gnu/libavutil/frame.h:319:13: note: declared here
     int64_t pkt_pts;
             ^~~~~~~
avcut.c:704:8: warning: ‘codec’ is deprecated [-Wdeprecated-declarations]
        pr->in_fctx->streams[stream_index]->codec->time_base);
        ^~
In file included from avcut.c:28:
/usr/include/x86_64-linux-gnu/libavformat/avformat.h:877:21: note: declared here
     AVCodecContext *codec;
                     ^~~~~
avcut.c:712:6: warning: ‘codec’ is deprecated [-Wdeprecated-declarations]
      pr->in_fctx->streams[stream_index]->codec->time_base);
      ^~
In file included from avcut.c:28:
/usr/include/x86_64-linux-gnu/libavformat/avformat.h:877:21: note: declared here
     AVCodecContext *codec;
                     ^~~~~
avcut.c: In function ‘main’:
avcut.c:967:2: warning: ‘av_register_all’ is deprecated [-Wdeprecated-declarations]
  av_register_all();
  ^~~~~~~~~~~~~~~
In file included from avcut.c:28:
/usr/include/x86_64-linux-gnu/libavformat/avformat.h:2025:6: note: declared here
 void av_register_all(void);
      ^~~~~~~~~~~~~~~
avcut.c:1001:3: warning: ‘codec’ is deprecated [-Wdeprecated-declarations]
   codec_ctx = pr->in_fctx->streams[i]->codec;
   ^~~~~~~~~
In file included from avcut.c:28:
/usr/include/x86_64-linux-gnu/libavformat/avformat.h:877:21: note: declared here
     AVCodecContext *codec;
                     ^~~~~
avcut.c:1004:3: warning: ‘refcounted_frames’ is deprecated [-Wdeprecated-declarations]
   codec_ctx->refcounted_frames = 1;
   ^~~~~~~~~
In file included from /usr/include/x86_64-linux-gnu/libavformat/avformat.h:319,
                 from avcut.c:28:
/usr/include/x86_64-linux-gnu/libavcodec/avcodec.h:2344:9: note: declared here
     int refcounted_frames;
         ^~~~~~~~~~~~~~~~~
avcut.c:1104:3: warning: ‘codec’ is deprecated [-Wdeprecated-declarations]
   dec_cctx = pr->in_fctx->streams[i]->codec;
   ^~~~~~~~
In file included from avcut.c:28:
/usr/include/x86_64-linux-gnu/libavformat/avformat.h:877:21: note: declared here
     AVCodecContext *codec;
                     ^~~~~
avcut.c:1105:3: warning: ‘codec’ is deprecated [-Wdeprecated-declarations]
   enc_cctx = out_stream->codec;
   ^~~~~~~~
In file included from avcut.c:28:
/usr/include/x86_64-linux-gnu/libavformat/avformat.h:877:21: note: declared here
     AVCodecContext *codec;
                     ^~~~~
avcut.c:1152:5: warning: ‘avcodec_copy_context’ is deprecated [-Wdeprecated-declarations]
     ret = avcodec_copy_context(enc_cctx, dec_cctx);
     ^~~
In file included from /usr/include/x86_64-linux-gnu/libavformat/avformat.h:319,
                 from avcut.c:28:
/usr/include/x86_64-linux-gnu/libavcodec/avcodec.h:4162:5: note: declared here
 int avcodec_copy_context(AVCodecContext *dest, const AVCodecContext *src);
     ^~~~~~~~~~~~~~~~~~~~
avcut.c:1188:4: warning: ‘avcodec_copy_context’ is deprecated [-Wdeprecated-declarations]
    ret = avcodec_copy_context(pr->out_fctx->streams[j]->codec, pr->in_fctx->streams[i]->codec);
    ^~~
In file included from /usr/include/x86_64-linux-gnu/libavformat/avformat.h:319,
                 from avcut.c:28:
/usr/include/x86_64-linux-gnu/libavcodec/avcodec.h:4162:5: note: declared here
 int avcodec_copy_context(AVCodecContext *dest, const AVCodecContext *src);
     ^~~~~~~~~~~~~~~~~~~~
avcut.c:1188:4: warning: ‘codec’ is deprecated [-Wdeprecated-declarations]
    ret = avcodec_copy_context(pr->out_fctx->streams[j]->codec, pr->in_fctx->streams[i]->codec);
    ^~~
In file included from avcut.c:28:
/usr/include/x86_64-linux-gnu/libavformat/avformat.h:877:21: note: declared here
     AVCodecContext *codec;
                     ^~~~~
avcut.c:1188:4: warning: ‘codec’ is deprecated [-Wdeprecated-declarations]
    ret = avcodec_copy_context(pr->out_fctx->streams[j]->codec, pr->in_fctx->streams[i]->codec);
    ^~~
In file included from avcut.c:28:
/usr/include/x86_64-linux-gnu/libavformat/avformat.h:877:21: note: declared here
     AVCodecContext *codec;
                     ^~~~~
avcut.c:1202:2: warning: ‘av_bitstream_filter_init’ is deprecated [-Wdeprecated-declarations]
  pr->bsf_h264_to_annexb = av_bitstream_filter_init("h264_mp4toannexb");
  ^~
In file included from /usr/include/x86_64-linux-gnu/libavformat/avformat.h:319,
                 from avcut.c:28:
/usr/include/x86_64-linux-gnu/libavcodec/avcodec.h:5784:27: note: declared here
 AVBitStreamFilterContext *av_bitstream_filter_init(const char *name);
                           ^~~~~~~~~~~~~~~~~~~~~~~~
avcut.c:1203:2: warning: ‘av_bitstream_filter_init’ is deprecated [-Wdeprecated-declarations]
  pr->bsf_dump_extra = av_bitstream_filter_init("dump_extra");
  ^~
In file included from /usr/include/x86_64-linux-gnu/libavformat/avformat.h:319,
                 from avcut.c:28:
/usr/include/x86_64-linux-gnu/libavcodec/avcodec.h:5784:27: note: declared here
 AVBitStreamFilterContext *av_bitstream_filter_init(const char *name);
                           ^~~~~~~~~~~~~~~~~~~~~~~~
avcut.c:1235:3: warning: ‘codec’ is deprecated [-Wdeprecated-declarations]
   av_log(NULL, AV_LOG_DEBUG, "codec:  " DUMP_TB(&pr->in_fctx->streams[i]->codec->time_base));
   ^~~~~~
In file included from avcut.c:28:
/usr/include/x86_64-linux-gnu/libavformat/avformat.h:877:21: note: declared here
     AVCodecContext *codec;
                     ^~~~~
avcut.c:1235:3: warning: ‘codec’ is deprecated [-Wdeprecated-declarations]
   av_log(NULL, AV_LOG_DEBUG, "codec:  " DUMP_TB(&pr->in_fctx->streams[i]->codec->time_base));
   ^~~~~~
In file included from avcut.c:28:
/usr/include/x86_64-linux-gnu/libavformat/avformat.h:877:21: note: declared here
     AVCodecContext *codec;
                     ^~~~~
avcut.c:1236:3: warning: ‘codec’ is deprecated [-Wdeprecated-declarations]
   av_log(NULL, AV_LOG_DEBUG, "ticks_per_frame: %d\n", pr->in_fctx->streams[i]->codec->ticks_per_frame);
   ^~~~~~
In file included from avcut.c:28:
/usr/include/x86_64-linux-gnu/libavformat/avformat.h:877:21: note: declared here
     AVCodecContext *codec;
                     ^~~~~
avcut.c:1239:3: warning: ‘codec’ is deprecated [-Wdeprecated-declarations]
   av_log(NULL, AV_LOG_DEBUG, "codec:  " DUMP_TB(&pr->out_fctx->streams[j]->codec->time_base));
   ^~~~~~
In file included from avcut.c:28:
/usr/include/x86_64-linux-gnu/libavformat/avformat.h:877:21: note: declared here
     AVCodecContext *codec;
                     ^~~~~
avcut.c:1239:3: warning: ‘codec’ is deprecated [-Wdeprecated-declarations]
   av_log(NULL, AV_LOG_DEBUG, "codec:  " DUMP_TB(&pr->out_fctx->streams[j]->codec->time_base));
   ^~~~~~
In file included from avcut.c:28:
/usr/include/x86_64-linux-gnu/libavformat/avformat.h:877:21: note: declared here
     AVCodecContext *codec;
                     ^~~~~
avcut.c:1240:3: warning: ‘codec’ is deprecated [-Wdeprecated-declarations]
   av_log(NULL, AV_LOG_DEBUG, "ticks_per_frame: %d\n", pr->out_fctx->streams[j]->codec->ticks_per_frame);
   ^~~~~~
In file included from avcut.c:28:
/usr/include/x86_64-linux-gnu/libavformat/avformat.h:877:21: note: declared here
     AVCodecContext *codec;
                     ^~~~~
avcut.c:1256:4: warning: ‘codec’ is deprecated [-Wdeprecated-declarations]
    if (pr->out_fctx->streams[j]->codec->time_base.den == 0)
    ^~
In file included from avcut.c:28:
/usr/include/x86_64-linux-gnu/libavformat/avformat.h:877:21: note: declared here
     AVCodecContext *codec;
                     ^~~~~
avcut.c:1260:4: warning: ‘codec’ is deprecated [-Wdeprecated-declarations]
    newo = pr->in_fctx->streams[i]->codec->gop_size;
    ^~~~
In file included from avcut.c:28:
/usr/include/x86_64-linux-gnu/libavformat/avformat.h:877:21: note: declared here
     AVCodecContext *codec;
                     ^~~~~
avcut.c:1261:4: warning: ‘codec’ is deprecated [-Wdeprecated-declarations]
    newo = 0 - pr->out_fctx->streams[j]->codec->ticks_per_frame *
    ^~~~
In file included from avcut.c:28:
/usr/include/x86_64-linux-gnu/libavformat/avformat.h:877:21: note: declared here
     AVCodecContext *codec;
                     ^~~~~
avcut.c:1262:5: warning: ‘codec’ is deprecated [-Wdeprecated-declarations]
     av_rescale_q(newo, pr->out_fctx->streams[j]->codec->time_base, pr->out_fctx->streams[j]->time_base);
     ^~~~~~~~~~~~
In file included from avcut.c:28:
/usr/include/x86_64-linux-gnu/libavformat/avformat.h:877:21: note: declared here
     AVCodecContext *codec;
                     ^~~~~
avcut.c:1287:3: warning: ‘codec’ is deprecated [-Wdeprecated-declarations]
   if (pr->in_fctx->streams[packet.stream_index]->codec->codec_type == AVMEDIA_TYPE_VIDEO) {
   ^~
In file included from avcut.c:28:
/usr/include/x86_64-linux-gnu/libavformat/avformat.h:877:21: note: declared here
     AVCodecContext *codec;
                     ^~~~~
avcut.c:1343:3: warning: ‘codec’ is deprecated [-Wdeprecated-declarations]
   if (!pr->out_fctx->streams[j]->codec->codec || !(pr->out_fctx->streams[j]->codec->codec->capabilities & AV_CODEC_CAP_DELAY))
   ^~
In file included from avcut.c:28:
/usr/include/x86_64-linux-gnu/libavformat/avformat.h:877:21: note: declared here
     AVCodecContext *codec;
                     ^~~~~
avcut.c:1343:3: warning: ‘codec’ is deprecated [-Wdeprecated-declarations]
   if (!pr->out_fctx->streams[j]->codec->codec || !(pr->out_fctx->streams[j]->codec->codec->capabilities & AV_CODEC_CAP_DELAY))
   ^~
In file included from avcut.c:28:
/usr/include/x86_64-linux-gnu/libavformat/avformat.h:877:21: note: declared here
     AVCodecContext *codec;
                     ^~~~~
avcut.c:1368:2: warning: ‘av_bitstream_filter_close’ is deprecated [-Wdeprecated-declarations]
  av_bitstream_filter_close(pr->bsf_h264_to_annexb);
  ^~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/x86_64-linux-gnu/libavformat/avformat.h:319,
                 from avcut.c:28:
/usr/include/x86_64-linux-gnu/libavcodec/avcodec.h:5801:6: note: declared here
 void av_bitstream_filter_close(AVBitStreamFilterContext *bsf);
      ^~~~~~~~~~~~~~~~~~~~~~~~~
avcut.c:1369:2: warning: ‘av_bitstream_filter_close’ is deprecated [-Wdeprecated-declarations]
  av_bitstream_filter_close(pr->bsf_dump_extra);
  ^~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/x86_64-linux-gnu/libavformat/avformat.h:319,
                 from avcut.c:28:
/usr/include/x86_64-linux-gnu/libavcodec/avcodec.h:5801:6: note: declared here
 void av_bitstream_filter_close(AVBitStreamFilterContext *bsf);
      ^~~~~~~~~~~~~~~~~~~~~~~~~
avcut.c:1375:3: warning: ‘codec’ is deprecated [-Wdeprecated-declarations]
   if (pr->out_fctx->streams[j]->codec && avcodec_is_open(pr->out_fctx->streams[j]->codec))
   ^~
In file included from avcut.c:28:
/usr/include/x86_64-linux-gnu/libavformat/avformat.h:877:21: note: declared here
     AVCodecContext *codec;
                     ^~~~~
avcut.c:1375:3: warning: ‘codec’ is deprecated [-Wdeprecated-declarations]
   if (pr->out_fctx->streams[j]->codec && avcodec_is_open(pr->out_fctx->streams[j]->codec))
   ^~
In file included from avcut.c:28:
/usr/include/x86_64-linux-gnu/libavformat/avformat.h:877:21: note: declared here
     AVCodecContext *codec;
                     ^~~~~
avcut.c:1376:4: warning: ‘codec’ is deprecated [-Wdeprecated-declarations]
    avcodec_close(pr->out_fctx->streams[j]->codec);
    ^~~~~~~~~~~~~
In file included from avcut.c:28:
/usr/include/x86_64-linux-gnu/libavformat/avformat.h:877:21: note: declared here
     AVCodecContext *codec;
                     ^~~~~
avcut.c:1380:3: warning: ‘codec’ is deprecated [-Wdeprecated-declarations]
   if (pr->in_fctx->streams[i]->codec) {
   ^~
In file included from avcut.c:28:
/usr/include/x86_64-linux-gnu/libavformat/avformat.h:877:21: note: declared here
     AVCodecContext *codec;
                     ^~~~~
avcut.c:1381:4: warning: ‘codec’ is deprecated [-Wdeprecated-declarations]
    av_freep(&pr->in_fctx->streams[i]->codec->opaque);
    ^~~~~~~~
In file included from avcut.c:28:
/usr/include/x86_64-linux-gnu/libavformat/avformat.h:877:21: note: declared here
     AVCodecContext *codec;
                     ^~~~~
avcut.c:1382:4: warning: ‘codec’ is deprecated [-Wdeprecated-declarations]
    if (avcodec_is_open(pr->in_fctx->streams[i]->codec))
    ^~
In file included from avcut.c:28:
/usr/include/x86_64-linux-gnu/libavformat/avformat.h:877:21: note: declared here
     AVCodecContext *codec;
                     ^~~~~
avcut.c:1383:5: warning: ‘codec’ is deprecated [-Wdeprecated-declarations]
     avcodec_close(pr->in_fctx->streams[i]->codec);
     ^~~~~~~~~~~~~
In file included from avcut.c:28:
/usr/include/x86_64-linux-gnu/libavformat/avformat.h:877:21: note: declared here
     AVCodecContext *codec;
                     ^~~~~
rd@h370:~/tmp.nobackup/avcut$

**Comment by anyc** [comment]
Sorry for the late response, I do not have much time to invest in avcut anymore.

I just released a new version where I fixed all warnings with ffmpeg 4.3 on Ubuntu 21.04. I just saw on another machine that there is another warning with 4.4 though. Thank you!
