### ISSUE TITLE
Update dependencies and compilation process in Readme.md

### ISSUE THREAD

**Issue by tobiisdesired** [anyc/avcut#17]
Hi,

could you please update the dependencies and the compilation process in the Readme.md. This information seems to be outdated for current Ubuntu versions.

**Comment by anyc** [comment]
Sorry for the late response, I do not have much time to invest in avcut anymore.

I just released a new version where I fixed lots deprecation warnings and which I tested with ffmpeg 4.3.1 on Ubuntu 21.04. It looks like ffmpeg did not change much with newer Ubuntu versions so chances are good that it will just work.

Please let me know if it does not work and I will reopen this issue.
