### ISSUE TITLE
Windows Build?

### ISSUE THREAD

**Issue by sharinganthief** [anyc/avcut#22]
sorry if this is the wrong place for this, but could there be a windows exe provided?

**Comment by anyc** [comment]
Sorry for the late response but I managed to create build that might work under Windows. Please try this test build: https://github.com/anyc/avcut/actions/runs/7747473779/artifacts/1213401760

Only the dynamically linked build worked so far. So you also have to download the ffmpeg libs from the link that is included in the archive and place the DLLs that are in the bin/ folder into the same directory as avcut.exe.
