### ISSUE TITLE
avcodec_get_context_defaults3 removed in new ffmpeg

### ISSUE THREAD

**Issue by Randrianasulu** [anyc/avcut#24]
without replacement.

https://lists.ffmpeg.org/pipermail/ffmpeg-cvslog/2016-June/100911.html

https://github.com/opencv/opencv/issues/24772

I just commented it out and added 

#include <libavcodec/bsf.h>

to very top of avcut.c file

it compiles with ffmpeg-6.1 but does not work ;)

**Comment by anyc** [comment]
Thanks for the report. I just added a few commits which should resolve issues with further deprecated parts. Please test.

I have another issue with a test video here. I will tag a new version after I have fixed this.

**Comment by Randrianasulu** [comment]
sadly on android/termux where I test it against ffmpeg 6.1 (termux is rolling collection of packages, so everything is fresh, compared to desktop Slackware 15.0) it runs into another error, but at least build is fixed so this ussue can be closed
